### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by QiaoK**
This merge request contains the new region transfer request APIs. Both documentation and regression tests are updated accordingly.

Several issues with data_server memory free and 1D read are fixed as well.

We checkpoint the current stable version now. The next step is to add aggregated APIs to this new domain and deprecate the old buf_map design (replacing old regression tests with new APIs).

### CODE REVIEW

**Comment by houjun** [comment]
@QiaoK We should also add metadata checkpoint capabilities for all the new I/O routines you implemented, so that PDC can support server restart. Please take a look at the checkpoint and restart functions in the pdc_server.c code.

**Comment by QiaoK** [comment]
> @QiaoK We should also add metadata checkpoint capabilities for all the new I/O routines you implemented, so that PDC can support server restart. Please take a look at the checkpoint and restart functions in the pdc_server.c code.

Region transfer requests are transient per client application (nothing to be stored to the server). This part does not require checkpointing at close_server. PDC also does regular checkpointing in case of failure. Afte failure recovery, shall we recover the unfinished client requests for region request transfers? Because clients are likely to fail as well, these transient requests are not useful anymore.

Other than region transfer request, I reused the infrastructures in "PDC_Server_data_write_out" and "PDC_Server_data_read_from" for the region by region implementation. The linked list "region_storage_head" is used and it is well checkpointed. The file flatten strategy reuses the existing object metadata.

**Comment by houjun** [comment]
Failure recovery can be tricky, if one server fails, we have to re-launch all the servers because of MPI, and clients probably need to re-establish mercury connection. 
Can you add a test for the checkpoint and restart verification, e.g. start server, clients create and write a few objects, close the server (bin/close_server, only need 1 rank to run), restart the server (add "restart" to the end of start server command), read the objects and verify the values.

**Comment by QiaoK** [comment]
Added a new test including 1D, 2D, and 3D with write, close, read pattern.

**Comment by QiaoK** [comment]
Close for now deal to annoying emails caused by debugging code.

**Comment by QiaoK** [comment]
All bugs are fixed. Redundant tests are cleaned from regression tests. Tested on Cori and data6 for correctness. Checkpoint also works for both vpic and bdcats (version 3)

**Review by houjun — APPROVED** [review]
looks good!

**Pull request merged**
