### PR TITLE
Fix obj_round_robin_io_all test code

### LINKED ISSUE #100: obj_round_robin_io_all.c test code
lines 111-113 look incorrect

> `111     mydata    = (char **)malloc(size * WRITE_REQ_SIZE);`
> `112     mydata[0] = (char *)malloc(my_data_size * type_size);`
> `113     mydata[1] = mydata[0] + my_data_size * type_size;`

### PR DESCRIPTION
**Pull request by houjun**
Fix #100

### CODE REVIEW

**Review by zhangwei217245 — APPROVED** [review]
LGTM

**Comment by jeanbez** [comment]
Is this test enabled in the CI? If not, could we enable it again to ensure it passes?

**Review by jeanbez — CHANGES_REQUESTED** [review]
Can we make sure this test in run in the CI?

**Comment by houjun** [comment]
@jeanbez Yes, this test is currently enabled in both serial and parallel tests.
obj_round_robin_io_1D/2D/3D

**Review by jeanbez — APPROVED** [review]

**Pull request merged**
