### PR TITLE
Fix NERSC CI issue for FindMercury

### PR DESCRIPTION
**Pull request by zhangwei217245**
For this one, we will make sure there is not need to add `-DCMAKE_PREFIX_PATH` flag in the CMake command line arg list.
Just remember that every time when we introduce a new external package, we have to append it to the CMAKE_PREFIX_PATH list in the main CMakeLists.txt. 

Tested on NERSC CI. PASSED.

Note: For Find_Package mechanism to be able to find a package and all its standard variables, setting CMAKE_PREFIX_PATH is inevitable and hence we need to either set it up in the main CMakeLists.txt file or we set it up via console args.

### CODE REVIEW

**Review by jeanbez — APPROVED** [review]

**Comment by jeanbez** [comment]
I would prefer this approach, @houjun any comments or preferences over the #98?

**Comment by houjun** [comment]
This looks good. Just need to add CMAKE_PREFIX_PATH to .gitlab-ci.yml

**Comment by zhangwei217245** [comment]
@houjun With this one, there will be no need to add CMAKE_PREFIX_PATH to .gitlab-ci.yml. For any external package, we can append $XXX_DIR to CMAKE_PREFIX_PATH in the main CMakeLists.txt .

**Comment by houjun** [comment]
OK.
@jeanbez, please go ahead with the merge once you verify it works with the CI on Perlmutter.
I'll close the other pull request.

**Comment by zhangwei217245** [comment]
> 

@jeanbez @houjun As I mentioned in the description of this PR, this change has been tested on a separate branch in the Gitlab repo and the building process in the CI system was working perfectly fine. https://software.nersc.gov/hpc-io/pdc/-/jobs/226125
We should be good to merge.

**Pull request merged**
