### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by QiaoK**
This commit checkpoints for cache implementation. Fixed code warnings from gcc7-9 compilers. Bug fixes include wrong pointer copy size and potential overflow of string copy size.

### CODE REVIEW

**Comment by houjun** [comment]
@QiaoK It seems the changes slow down the test significantly with github actions run, even after changing the mercury trigger timeout and count value, see https://github.com/hpc-io/pdc/runs/2935686052 (timed out after 1h) and https://github.com/hpc-io/pdc/runs/2936367378 (30m+ and still running)

**Comment by QiaoK** [comment]
I think it may be the issue with github server. I tested ctests locally and on Cori. There is no significant performance difference.

**Comment by houjun** [comment]
@QiaoK I just manually run the tests on the stable branch, it finishes in a few minutes [HERE](https://github.com/hpc-io/pdc/runs/2946109680?check_suite_focus=true), so there is probably something changed in this pull request that causes the slowdown.

**Review by houjun — APPROVED** [review]
passed all tests, @QiaoK any further changes before merge?

**Pull request merged**
