### PR TITLE
update VPIC output timing precision

### PR DESCRIPTION
**Pull request by jeanbez**
Update VPIC timing precision to `%.5f` instead of `%.2f`.

### CODE REVIEW

**Comment by houjun** [comment]
@jeanbez Shall we change them to scientific notation, %.5e?

**Comment by jeanbez** [comment]
> @jeanbez Shall we change them to scientific notation, %.5e?

@houjun Either would be ok for me; maybe this will be even better. Should we do that for the other examples to maintain consistency in the reports or just for VPIC?

**Comment by houjun** [comment]
Yes, we can change other codes to use the same format.

**Comment by jeanbez** [comment]
@houjun updated all the tests where we had `%.6f` or `%.4f` (all of them time-related metrics) to `%.5e`.

**Review by houjun — APPROVED** [review]

**Pull request merged**
