### PR TITLE
fix warnings, commenting off 'find_path' and 'find_library' for Mercury in src/commons/CMakeLists.txt 

### PR DESCRIPTION
**Pull request by zhangwei217245**
I fixed all the warnings that I can fix throughout the entire project, and also suppressed some trivial warnings (they are either not accurate in reflecting the errors or only help little in ensuring code correctness.)

Also, per Dr. Tang's request, I commented off 'find_path' and 'find_library' directives in src/commons/CMakeLists.txt. But we need to discuss about the dependency management of the project with CMake, especially the standard of using CMake find_package directive.

Additionally, this PR fixes some of the length issues for server address strings, temp dir strings, hostnames and object/app names. This will ensure that no potential memory leak for snprintf.

### CODE REVIEW

**Comment by zhangwei217245** [comment]
I fixed all the warnings that I can fix throughout the entire project, and also suppressed some trivial warnings (they are either not accurate in reflecting the errors or only help little in ensuring code correctness.)

Also, per Dr. Tang's request, I commented off '`find_path`' and '`find_library`' directives in src/commons/CMakeLists.txt. But we need to discuss about the dependency management of the project with CMake, especially the standard of using CMake `find_package` directive.

**Comment by zhangwei217245** [comment]
image

**Comment by jeanbez** [comment]
@zhangwei217245 what is the dependency problem we are having that CMake cannot identify?

**Comment by zhangwei217245** [comment]
> @zhangwei217245 what is the dependency problem we are having that CMake cannot identify?

By default, `find_package()` directive should be able to capture `XXX_INCLUDE_DIR` (suppose XXX is the package name we are trying to find). However, for Mercury, calling `find_package(MERCURY) `doesn't materialize `MERCURY_INCLUDE_DIR` variable but this variable is included as part of `PDC_EXT_INCLUDE_DEPENDENCIES` (line 29 in `src/commons/CMakeLists.txt` and line 45 of `src/api/CMakeLists.txt` in the current develop branch) . 

I have encountered an issue when compiling on my own machine which shows that `mercury_atomic.h` could not be found when the compiler was trying to process `pdc_id_pkg.h`. (Though this is not reproduced now). And this is why I noticed that MERCURY_INCLUDE_DIR is not materialized.

Though currently the project can compile without a problem showing "`mercury.h`" cannot be found, it doesn't mean we will never need  MERCURY_INCLUDE_DIR to be materialized. Plus, 

With the CMake convention that XXX_INCLUDE_DIR should be addressed when package is found, I suggest to 
1. make sure XXX_INCLUDE_DIR is materialized whenever find_package is called
2. containing FindXXX.cmake file in our project to help with the search of XXX packages in CMake.

**Review by houjun — APPROVED** [review]

**Pull request merged**
